In [1]:
import numpy as np
import noise3d

In [2]:
from noise3d import confidence
from noise3d import genseq
from noise3d import noise

In [3]:
import scipy

In [4]:
scipy.__version__

'1.2.1'

In [5]:
proba = 0.95
T = 100
V = 100
H = 100
VH = V*H
#sigmas = np.arange(1, 8)
sigmas = (10, 20, 20, 10, 10, 50, 50)

seq = genseq.genseq_3dnoise_seq(T, V, H, sigmas)

N_tirage = 10

for i in range(N_tirage):
    pass


In [6]:
confidence.dof_of_sigmaDs(T, V, H)

array([[    100,       0,       0,     100,     100,       0,     100],
       [      0,     100,       0,     100,       0,     100,     100],
       [      0,       0,     100,       0,     100,     100,     100],
       [    100,     100,       0,   10000,     100,     100,   10000],
       [    100,       0,     100,     100,   10000,     100,   10000],
       [      0,     100,     100,     100,     100,   10000,   10000],
       [    100,     100,     100,   10000,   10000,   10000, 1000000]])

In [7]:
sigmas_est = noise.get_all_3d_corrected_var_matrix(seq)

interm, scale, Nv, var_sigmaDs, var_pred_matricies, covariance_matricies_of_sigmaDs, covariance_matricies_of_sigmas, variances_of_sigmas, CI = confidence.compute_CI(proba, T, V, H, V*H, sigmas_est)



NameError: name 'Tv' is not defined

In [8]:
interm.shape

NameError: name 'interm' is not defined

In [49]:
interm

array([[1.00000000e+01, 0.00000000e+00, 0.00000000e+00, 1.00000000e-01,
        1.00000000e-01, 0.00000000e+00, 5.00000000e-03],
       [0.00000000e+00, 2.00000000e+01, 0.00000000e+00, 1.00000000e-01,
        0.00000000e+00, 5.00000000e-01, 5.00000000e-03],
       [0.00000000e+00, 0.00000000e+00, 2.00000000e+01, 0.00000000e+00,
        1.00000000e-01, 5.00000000e-01, 5.00000000e-03],
       [9.90099010e+00, 1.98019802e+01, 0.00000000e+00, 1.00000000e+01,
        9.90099010e-02, 4.95049505e-01, 5.00000000e-01],
       [9.90099010e+00, 0.00000000e+00, 1.98019802e+01, 9.90099010e-02,
        1.00000000e+01, 4.95049505e-01, 5.00000000e-01],
       [0.00000000e+00, 1.98019802e+01, 1.98019802e+01, 9.90099010e-02,
        9.90099010e-02, 5.00000000e+01, 5.00000000e-01],
       [9.90000990e+00, 1.98000198e+01, 1.98000198e+01, 9.99901000e+00,
        9.99901000e+00, 4.99950500e+01, 5.00000000e+01]])

In [50]:
scale.shape

(7, 7)

In [51]:
scale

array([[ 1.01010101e-01, -0.00000000e+00, -0.00000000e+00,
         1.01010101e-03,  1.01010101e-03, -0.00000000e+00,
         5.05050505e-05],
       [-0.00000000e+00,  2.02020202e-01, -0.00000000e+00,
         1.01010101e-03, -0.00000000e+00,  5.05050505e-03,
         5.05050505e-05],
       [-0.00000000e+00, -0.00000000e+00,  2.02020202e-01,
        -0.00000000e+00,  1.01010101e-03,  5.05050505e-03,
         5.05050505e-05],
       [ 1.00010001e-01,  2.00020002e-01, -0.00000000e+00,
         1.00010001e-03,  1.00010001e-03,  5.00050005e-03,
         5.00050005e-05],
       [ 1.00010001e-01, -0.00000000e+00,  2.00020002e-01,
         1.00010001e-03,  1.00010001e-03,  5.00050005e-03,
         5.00050005e-05],
       [-0.00000000e+00,  2.00020002e-01,  2.00020002e-01,
         1.00010001e-03,  1.00010001e-03,  5.00050005e-03,
         5.00050005e-05],
       [ 1.00000100e-01,  2.00000200e-01,  2.00000200e-01,
         1.00000100e-03,  1.00000100e-03,  5.00000500e-03,
         5.0000050

In [52]:
Nv.shape

(7, 7)

In [53]:
Nv

array([[    99,     -1,     -1,     99,     99,     -1,     99],
       [    -1,     99,     -1,     99,     -1,     99,     99],
       [    -1,     -1,     99,     -1,     99,     99,     99],
       [    99,     99,     -1,   9999,     99,     99,   9999],
       [    99,     -1,     99,     99,   9999,     99,   9999],
       [    -1,     99,     99,     99,     99,   9999,   9999],
       [    99,     99,     99,   9999,   9999,   9999, 999999]])

In [54]:
M = noise3d.noise.compute_M_corrected(T, V, H, VH)
np.linalg.inv(M)*var_sigmaDs

array([[ 2.06122030e+00, -0.00000000e+00, -0.00000000e+00,
        -2.08183251e-06, -2.08183251e-06,  0.00000000e+00,
         5.20509657e-11],
       [-0.00000000e+00,  8.24488122e+00, -0.00000000e+00,
        -2.08183251e-06,  0.00000000e+00, -5.20458127e-05,
         5.20509657e-11],
       [-0.00000000e+00, -0.00000000e+00,  8.24488122e+00,
         0.00000000e+00, -2.08183251e-06, -5.20458127e-05,
         5.20509657e-11],
       [-2.02060612e+00, -8.08242448e+00,  0.00000000e+00,
         2.06122030e-02,  2.04081218e-06,  5.10203046e-05,
        -5.15356096e-07],
       [-2.02060612e+00,  0.00000000e+00, -8.08242448e+00,
         2.04081218e-06,  2.06122030e-02,  5.10203046e-05,
        -5.15356096e-07],
       [ 0.00000000e+00, -8.08242448e+00, -8.08242448e+00,
         2.04081218e-06,  2.04081218e-06,  5.15305076e-01,
        -5.15356096e-07],
       [ 2.02020606e+00,  8.08082424e+00,  8.08082424e+00,
        -2.06081220e-02, -2.06081220e-02, -5.15203051e-01,
         5.1530507

In [55]:
var_sigmaDs

array([[ 2.02020202e+00, -0.00000000e+00, -0.00000000e+00,
         2.02020202e-04,  2.02020202e-04, -0.00000000e+00,
         5.05050505e-07],
       [-0.00000000e+00,  8.08080808e+00, -0.00000000e+00,
         2.02020202e-04, -0.00000000e+00,  5.05050505e-03,
         5.05050505e-07],
       [-0.00000000e+00, -0.00000000e+00,  8.08080808e+00,
        -0.00000000e+00,  2.02020202e-04,  5.05050505e-03,
         5.05050505e-07],
       [ 1.98039606e+00,  7.92158424e+00, -0.00000000e+00,
         2.00020002e-02,  1.98039606e-04,  4.95099015e-03,
         5.00050005e-05],
       [ 1.98039606e+00, -0.00000000e+00,  7.92158424e+00,
         1.98039606e-04,  2.00020002e-02,  4.95099015e-03,
         5.00050005e-05],
       [-0.00000000e+00,  7.92158424e+00,  7.92158424e+00,
         1.98039606e-04,  1.98039606e-04,  5.00050005e-01,
         5.00050005e-05],
       [ 1.98000396e+00,  7.92001584e+00,  7.92001584e+00,
         1.99980400e-02,  1.99980400e-02,  4.99951000e-01,
         5.0000050

In [56]:
var_sigmaDs[:,0]

array([ 2.02020202, -0.        , -0.        ,  1.98039606,  1.98039606,
       -0.        ,  1.98000396])

In [57]:
covariance_matricies_of_sigmaDs

array([[3.18439924e+01, 0.00000000e+00, 0.00000000e+00, 3.18439924e+01,
        3.18439924e+01, 0.00000000e+00, 3.18439924e+01],
       [0.00000000e+00, 1.27375970e+02, 0.00000000e+00, 1.27375970e+02,
        0.00000000e+00, 1.27375970e+02, 1.27375970e+02],
       [0.00000000e+00, 0.00000000e+00, 1.27375970e+02, 0.00000000e+00,
        1.27375970e+02, 1.27375970e+02, 1.27375970e+02],
       [8.24164044e-02, 8.24164044e-02, 4.08001598e-02, 8.32324892e-02,
        8.24164044e-02, 8.24164044e-02, 8.32324892e-02],
       [8.24164044e-02, 4.08001598e-02, 8.24164044e-02, 8.24164044e-02,
        8.32324892e-02, 8.24164044e-02, 8.32324892e-02],
       [1.02000400e+00, 2.06041011e+00, 2.06041011e+00, 2.06041011e+00,
        2.06041011e+00, 2.08081223e+00, 2.08081223e+00],
       [5.25509131e-03, 5.25509131e-03, 5.25509131e-03, 5.30712187e-03,
        5.30712187e-03, 5.30712187e-03, 5.30762682e-03]])

In [58]:
covariance_matricies_of_sigmas.shape

(7, 7)

In [59]:
covariance_matricies_of_sigmas

array([[3.31502443e+01, 0.00000000e+00, 0.00000000e+00, 3.34817467e-01,
        3.34817467e-01, 0.00000000e+00, 3.34850618e-03],
       [0.00000000e+00, 1.32600977e+02, 0.00000000e+00, 1.33926987e+00,
        0.00000000e+00, 1.33926987e+00, 1.33940247e-02],
       [0.00000000e+00, 0.00000000e+00, 1.32600977e+02, 0.00000000e+00,
        1.33926987e+00, 1.33926987e+00, 1.33940247e-02],
       [8.66551262e-04, 8.66551262e-04, 4.28985348e-08, 8.83883145e-02,
        8.75216775e-06, 8.75216775e-06, 8.83970658e-04],
       [8.66551262e-04, 4.28985348e-08, 8.66551262e-04, 8.75216775e-06,
        8.83883145e-02, 8.75216775e-06, 8.83970658e-04],
       [1.07246337e-06, 2.16637815e-02, 2.16637815e-02, 2.18804194e-04,
        2.18804194e-04, 2.20970786e+00, 2.20992665e-02],
       [5.52591067e-07, 5.52591067e-07, 5.52591067e-07, 5.63642883e-05,
        5.63642883e-05, 5.63642883e-05, 5.63752323e-03]])

In [60]:
variances_of_sigmas.shape

(7,)

In [61]:
variances_of_sigmas

array([3.31502443e+01, 1.32600977e+02, 1.32600977e+02, 8.83883145e-02,
       8.83883145e-02, 2.20970786e+00, 5.63752323e-03])

In [62]:
import scipy


In [63]:
scipy.stats.norm

In [64]:
CI

(array([-6.49732849e+01, -2.59893140e+02, -2.59893140e+02, -1.73237913e-01,
        -1.73237913e-01, -4.33094783e+00, -1.10493425e-02]),
 array([6.49732849e+01, 2.59893140e+02, 2.59893140e+02, 1.73237913e-01,
        1.73237913e-01, 4.33094783e+00, 1.10493425e-02]))