In [1]:
import numpy as np
import numpy.ma as ma

In [34]:
data = np.mgrid[0:4, -2:3][0]
data

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3]])

In [35]:
mdata = data.view(ma.MaskedArray)
mdata

masked_array(
  data=[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3]],
  mask=False,
  fill_value=999999)

In [36]:
mdata.mask

False

In [37]:
mdata.mask = [[True, True, False, False, True],
              [True, True, False, False, True],
              [True, True, False, False, True],
              [True, True, False, False, True],
              [True, True, False, False, True]]

In [38]:
mdata

masked_array(
  data=[[--, --, 0, 0, --],
        [--, --, 1, 1, --],
        [--, --, 2, 2, --],
        [--, --, 3, 3, --]],
  mask=[[ True,  True, False, False,  True],
        [ True,  True, False, False,  True],
        [ True,  True, False, False,  True],
        [ True,  True, False, False,  True]],
  fill_value=999999)

In [46]:
print(np.mean(data, axis=0, keepdims=True))
print(np.mean(mdata, axis=0, keepdims=True))

print(np.mean(data, axis=1, keepdims=True))
print(np.mean(mdata, axis=1, keepdims=True))

[[1.5 1.5 1.5 1.5 1.5]]
[[-- -- 1.5 1.5 --]]
[[0.]
 [1.]
 [2.]
 [3.]]
[[0.0]
 [1.0]
 [2.0]
 [3.0]]


In [40]:
data

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3]])

In [45]:
#print(data.count(axis=0))
#print(data.count(axis=1))
print(mdata.count(axis=0))
print(mdata.count(axis=1))

[0 0 4 4 0]
[2 2 2 2]


In [52]:
data = np.array([1,2,3,4,5])
print(np.mean(data))
print(np.var(data))

3.0
2.0


In [54]:
data = data.view(ma.MaskedArray)
data.mask =[True, True, True, False, False]
print(np.mean(data))
print(np.var(data))
print(((0.5)**2 + (0.5)**2)/2)

4.5
0.25
0.25


In [58]:
data.count()

2

In [74]:
data = np.array([
    [1, 2, 3],
    [1, 2, 3],
    [1, 2, 3],
])
print(data<2)
data = data.view(ma.MaskedArray)
data.mask = data<2


[[ True False False]
 [ True False False]
 [ True False False]]


In [75]:
data

masked_array(
  data=[[--, 2, 3],
        [--, 2, 3],
        [--, 2, 3]],
  mask=[[ True, False, False],
        [ True, False, False],
        [ True, False, False]],
  fill_value=999999)

In [80]:
np.ma.shape(data)

(3, 3)

In [15]:
print(data.count(axis=0))
print(data.count(axis=1))


AttributeError: 'numpy.ndarray' object has no attribute 'count'

In [28]:
data = np.random.rand(3, 3, 3)

In [29]:
import noise3d

In [30]:
print(noise3d.get_all_3d_noise_var_fast(data))
print(noise3d.get_all_3D_noise_var(data))
print(noise3d.get_all_3d_corrected_var_matrix(data))

((0.002680112688535366, 0.0028168077277776517, 0.003744412479418759, 0.012440063409212634, 0.02056137932939468, 0.030633007893311283, 0.012519041037551859), 0.08539482456520223)
((0.002680112688535359, 0.0028168077277776556, 0.003744412479418762, 0.012440063409212635, 0.020561379329394672, 0.030633007893311286, 0.020257485823309197), 0.08539482456520223)
((-0.012005645923230071, -0.01858336992659887, -0.02306997578841244, 0.0029345171765069802, 0.019177149016871037, 0.03932040614470428, 0.06583682892575488), 0.0736099096255958)


In [40]:
mdata = data.view(np.ma.MaskedArray)
print(noise3d.get_all_3d_noise_var_fast(data))
print(noise3d.get_all_3D_noise_var(data))
print(noise3d.get_all_3d_corrected_var_matrix(data))

((0.002680112688535366, 0.0028168077277776517, 0.003744412479418759, 0.012440063409212634, 0.02056137932939468, 0.030633007893311283, 0.012519041037551859), 0.08539482456520223)
((0.002680112688535359, 0.0028168077277776556, 0.003744412479418762, 0.012440063409212635, 0.020561379329394672, 0.030633007893311286, 0.020257485823309197), 0.08539482456520223)
((-0.012005645923230071, -0.01858336992659887, -0.02306997578841244, 0.0029345171765069802, 0.019177149016871037, 0.03932040614470428, 0.06583682892575488), 0.0736099096255958)


In [41]:
print(mdata[0]<0.2)
mdata.mask = mdata[0]<0.2
print()
print(mdata.mask)
print(mdata)

[[False False False]
 [False  True False]
 [ True False False]]

[[[False False False]
  [False  True False]
  [ True False False]]

 [[False False False]
  [False  True False]
  [ True False False]]

 [[False False False]
  [False  True False]
  [ True False False]]]
[[[0.5313909403716847 0.7653768298798973 0.8179162597755274]
  [0.38430207548624373 -- 0.6662525555890021]
  [-- 0.3704051720980961 0.7125368676288137]]

 [[0.840607318757571 0.5451527277251371 0.12227806166022048]
  [0.04945802622302997 -- 0.8638085909796172]
  [-- 0.8987479714458132 0.2268290197264886]]

 [[0.706391662681436 0.9813086644945774 0.03086747173996407]
  [0.8294233352124546 -- 0.843726794968146]
  [-- 0.7640337606757949 0.2587341885764959]]]


In [36]:
print(np.ma.count(mdata, axis=0))
print(mdata.shape)
print(np.ma.count(data, axis=0))
print(data.shape)
print(np.ma.count(data, axis=(1,2)))

[[3 3 3]
 [3 0 3]
 [0 3 3]]
(3, 3, 3)
[[3 3 3]
 [3 3 3]
 [3 3 3]]
(3, 3, 3)
[9 9 9]


In [14]:
print(noise3d.get_all_3d_noise_var_fast(mdata))
print(noise3d.get_all_3D_noise_var(mdata))
print(noise3d.get_all_3d_corrected_var_matrix(mdata))

((0.0006903371046662722, 0.0005672438759804979, 0.0002595626458543249, 0.005460066768930252, 0.007677068203833366, 0.0069542309996983315, 0.0458294267182969), 0.06743793631725994)
((0.0006569692791428738, 0.0004178694667720489, 0.00024219685903648035, 0.005281921078933931, 0.00718754138134673, 0.006724039579795409, 0.047138824998500806), 0.06743793631725994)
((-0.00026781031552104, -0.00038387185710667544, -0.0009321573663165455, 0.00031733002282694346, 0.0029234792007902383, 0.0022669794968026846, 0.06340664978255944), 0.06733059896403505)
